### PR TITLE
Aw/refactor configs update

### PR DESCRIPTION
**Pull request by ashton314**

### CODE REVIEW

**Comment by bennn** [comment]
Add a script to run everything. A really simple one: `julia dir/file.jl` for each target.

**Comment by ashton314** [comment]
> Add a script to run everything. A really simple one: `julia dir/file.jl` for each target.

Done. I added the files one-by-one, as there are some Julia files we *don't* want to run with this (playground.jl is an example).

I've left space for scripts in the `metalhead` and `FPBench` folders—we can add those later.

**Comment by bennn** [comment]
where is the script?

**Comment by ashton314** [comment]
@bennn Oops. Pushed `run_all.sh` just now

**Pull request merged**
